encryptionsalt: v1:1bNyokdZdk8=:v1:qV7O5Au0mL5z8h+Q:1RUOBEdqphUT6KWNvMoQQ3Asa9XeSQ==
config:
  aws:region: us-east-1
  recetalias:errorDocument: index.html
  recetalias:indexDocument: index.html
  recetalias:path: ../build
