backend:
  name: proxy
  proxy_url: http://localhost:8081/api/v1
  branch: main

site_url: https://recetalias.com

media_folder: static/images/uploads
public_folder: /images/uploads

locale: es

collections:
  - name: 'ingredients'
    label: 'Ingredientes'
    files:
      - name: 'all-ingredients'
        label: 'Todos los ingredientes'
        file: 'src/lib/data/ingredients.json'
        fields:
          - label: 'Ingredientes'
            name: 'ingredients'
            widget: 'list'
            label_singular: 'Ingrediente'
            collapsed: true
            summary: '{{fields.name}} ({{fields.id}})'
            fields:
              - { label: 'Nombre', name: 'name', widget: 'string', required: true }

  - name: 'recipes'
    label: 'Recetas'
    files:
      - name: 'all-recipes'
        label: 'Todas las recetas'
        file: 'src/lib/data/recipes.json'
        fields:
          - label: 'Recetas'
            name: 'recipes'
            widget: 'list'
            label_singular: 'Receta'
            collapsed: true
            summary: '{{fields.title}} (/recetas/{{fields.id}})'
            fields:
              - { label: 'ID', name: 'id', widget: 'string', required: true, pattern: ['^[a-z0-9-]+$', 'Solo letras minúsculas, números y guiones'], hint: 'Compone el URL de la receta, no cambiarlo frecuentemente' }
              - { label: 'Título', name: 'title', widget: 'string', required: true }
              - { label: 'Descripción', name: 'description', widget: 'text', required: true }
              - label: 'Ingredientes'
                name: 'ingredients'
                widget: 'list'
                required: true
                label_singular: 'Ingrediente'
                collapsed: false
                summary: '{{fields.ingredientDetail}}'
                min: 1
                fields:
                  - label: 'Ingrediente para búsqueda (no se va a incluir en la entrada del blog)'
                    name: 'ingredientId'
                    widget: 'relation'
                    collection: 'ingredients'
                    file: 'all-ingredients'
                    search_fields: ['ingredients.*.name', 'ingredients.*.id']
                    display_fields: ['ingredients.*.name']
                    value_field: 'ingredients.*.id'
                    required: true
                    hint: 'Este campo se va a usar únicamente para la búsqueda, no se visualiza en la entrada del blog'
                  - label: 'Ingrediente'
                    name: 'ingredientDetail'
                    widget: 'string'
                    required: true
                    hint: 'Ejemplo: 2 cucharadas de sal'
              - label: 'Fecha'
                name: 'date'
                widget: 'datetime'
                date_format: 'DD/MM/YYYY'
                time_format: false
                format: 'YYYY-MM-DD'
                required: true
              - label: 'Imagen'
                name: 'image'
                widget: 'object'
                collapsed: false
                fields:
                  - { label: 'URL', name: 'url', widget: 'image', required: true }
                  - { label: 'Texto alternativo', name: 'alt', widget: 'string', required: true }
              - label: 'Instrucciones'
                name: 'instructions'
                widget: 'list'
                field: { label: 'Paso', name: 'step', widget: 'text' }

